In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

import os

import acquire
import wrangle
import acquire_all_counties
import acquire_all_counties_luke

All counties luke functions imported successfully.

In [2]:
svidf, casesdf, zipsdf, cpopdf = acquire_all_counties_luke.get_county_data()

Enter the requested date in YYYY-MM-DD format: 2020-12-08
Enter the requested state full name: texas
Enter the requested full name of county: bexar
(363, 124)
(1, 6)
(70, 4)
(1, 3)

In [4]:
# Ideas to make this input better:
# For the state and county choices, create a dictionary or list of each, and run an if loop making sure an input exists. If not, bounce back an error message and have the user input again until it the correct county is created. So an if/else loop.
# For the date entry, there has got to be a way I can find online to improve that, just so an erroneous date entry doesn't screw up the function.

In [5]:
svidf.head()

,st,state,st_abbr,stcnty,county,fips,location,area_sqmi,e_totpop,m_totpop,...,f_crowd,f_noveh,f_groupq,f_theme4,f_total,e_uninsur,m_uninsur,ep_uninsur,mp_uninsur,e_daypop
38447,48,TEXAS,TX,48029,Bexar,48029120300,"Census Tract 1203, Bexar County, Texas",1.841380,8193,23,...,0,0,0,0,0,258,194,3.2,2.4,7963
38448,48,TEXAS,TX,48029,Bexar,48029120400,"Census Tract 1204, Bexar County, Texas",1.815195,6115,209,...,0,0,0,0,0,86,87,1.4,1.5,3018
38449,48,TEXAS,TX,48029,Bexar,48029120501,"Census Tract 1205.01, Bexar County, Texas",2.472439,9447,992,...,0,0,0,0,0,1778,424,19.2,4.0,8461
38450,48,TEXAS,TX,48029,Bexar,48029120600,"Census Tract 1206, Bexar County, Texas",1.269029,5889,747,...,0,0,0,0,0,782,330,13.5,4.8,5026
38451,48,TEXAS,TX,48029,Bexar,48029120800,"Census Tract 1208, Bexar County, Texas",1.868609,6803,421,...,0,0,0,0,0,411,245,6.1,3.5,4990

In [6]:
casesdf

              date county  state     fips  cases  deaths
809562  2020-12-08  Bexar  Texas  48029.0  89502  1544.0

In [7]:
zipsdf

      state_name county_name    zip  population
27017      Texas       Bexar  78002        7329
27030      Texas       Bexar  78015       15119
27036      Texas       Bexar  78023       31003
27068      Texas       Bexar  78073        8893
27071      Texas       Bexar  78101        6175
...          ...         ...    ...         ...
27167      Texas       Bexar  78259       26508
27168      Texas       Bexar  78260       27696
27169      Texas       Bexar  78261       17127
27170      Texas       Bexar  78263        5208
27171      Texas       Bexar  78264       11174

[70 rows x 4 columns]

In [8]:
cpopdf

      STATE COUNTY  E_TOTPOP
2653  TEXAS  Bexar   1925865

In [17]:
cpopdf.columns = cpopdf.columns.str.lower()
cpopdf

      state county  e_totpop
2653  TEXAS  Bexar   1925865

In [11]:
svidf.head()

,st,state,st_abbr,stcnty,county,fips,location,area_sqmi,e_totpop,m_totpop,...,f_crowd,f_noveh,f_groupq,f_theme4,f_total,e_uninsur,m_uninsur,ep_uninsur,mp_uninsur,e_daypop
38447,48,TEXAS,TX,48029,Bexar,48029120300,"Census Tract 1203, Bexar County, Texas",1.841380,8193,23,...,0,0,0,0,0,258,194,3.2,2.4,7963
38448,48,TEXAS,TX,48029,Bexar,48029120400,"Census Tract 1204, Bexar County, Texas",1.815195,6115,209,...,0,0,0,0,0,86,87,1.4,1.5,3018
38449,48,TEXAS,TX,48029,Bexar,48029120501,"Census Tract 1205.01, Bexar County, Texas",2.472439,9447,992,...,0,0,0,0,0,1778,424,19.2,4.0,8461
38450,48,TEXAS,TX,48029,Bexar,48029120600,"Census Tract 1206, Bexar County, Texas",1.269029,5889,747,...,0,0,0,0,0,782,330,13.5,4.8,5026
38451,48,TEXAS,TX,48029,Bexar,48029120800,"Census Tract 1208, Bexar County, Texas",1.868609,6803,421,...,0,0,0,0,0,411,245,6.1,3.5,4990

In [13]:
svidf['total_pop'] = svidf.e_totpop.sum()

In [14]:
svidf.head()

,st,state,st_abbr,stcnty,county,fips,location,area_sqmi,e_totpop,m_totpop,...,f_noveh,f_groupq,f_theme4,f_total,e_uninsur,m_uninsur,ep_uninsur,mp_uninsur,e_daypop,total_pop
38447,48,TEXAS,TX,48029,Bexar,48029120300,"Census Tract 1203, Bexar County, Texas",1.841380,8193,23,...,0,0,0,0,258,194,3.2,2.4,7963,1925865
38448,48,TEXAS,TX,48029,Bexar,48029120400,"Census Tract 1204, Bexar County, Texas",1.815195,6115,209,...,0,0,0,0,86,87,1.4,1.5,3018,1925865
38449,48,TEXAS,TX,48029,Bexar,48029120501,"Census Tract 1205.01, Bexar County, Texas",2.472439,9447,992,...,0,0,0,0,1778,424,19.2,4.0,8461,1925865
38450,48,TEXAS,TX,48029,Bexar,48029120600,"Census Tract 1206, Bexar County, Texas",1.269029,5889,747,...,0,0,0,0,782,330,13.5,4.8,5026,1925865
38451,48,TEXAS,TX,48029,Bexar,48029120800,"Census Tract 1208, Bexar County, Texas",1.868609,6803,421,...,0,0,0,0,411,245,6.1,3.5,4990,1925865

In [16]:
svidf['pop_perc'] = (svidf.e_totpop / svidf.total_pop)

In [22]:
# Now merge the total cases into a new column:

# pd.merge(svidf, cpopdf[['county', 'e_totpop']], on = 'county', how = 'left')

In [23]:
casesdf

              date county  state     fips  cases  deaths
809562  2020-12-08  Bexar  Texas  48029.0  89502  1544.0

In [25]:
pd.merge(svidf, casesdf[['county', 'fips', 'cases', 'deaths']], on = 'county')

,st,state,st_abbr,stcnty,county,fips_x,location,area_sqmi,e_totpop,m_totpop,...,e_uninsur,m_uninsur,ep_uninsur,mp_uninsur,e_daypop,total_pop,pop_perc,fips_y,cases,deaths
0,48,TEXAS,TX,48029,Bexar,48029120300,"Census Tract 1203, Bexar County, Texas",1.841380,8193,23,...,258,194,3.2,2.4,7963,1925865,0.004254,48029.0,89502,1544.0
1,48,TEXAS,TX,48029,Bexar,48029120400,"Census Tract 1204, Bexar County, Texas",1.815195,6115,209,...,86,87,1.4,1.5,3018,1925865,0.003175,48029.0,89502,1544.0
2,48,TEXAS,TX,48029,Bexar,48029120501,"Census Tract 1205.01, Bexar County, Texas",2.472439,9447,992,...,1778,424,19.2,4.0,8461,1925865,0.004905,48029.0,89502,1544.0
3,48,TEXAS,TX,48029,Bexar,48029120600,"Census Tract 1206, Bexar County, Texas",1.269029,5889,747,...,782,330,13.5,4.8,5026,1925865,0.003058,48029.0,89502,1544.0
4,48,TEXAS,TX,48029,Bexar,48029120800,"Census Tract 1208, Bexar County, Texas",1.868609,6803,421,...,411,245,6.1,3.5,4990,1925865,0.003532,48029.0,89502,1544.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358,48,TEXAS,TX,48029,Bexar,48029190100,"Census Tract 1901, Bexar County, Texas",0.637452,3801,555,...,825,241,23.0,6.0,5348,1925865,0.001974,48029.0,89502,1544.0
359,48,TEXAS,TX,48029,Bexar,48029191410,"Census Tract 1914.10, Bexar County, Texas",0.603601,5024,568,...,1235,392,24.6,7.2,3125,1925865,0.002609,48029.0,89502,1544.0
360,48,TEXAS,TX,48029,Bexar,48029980100,"Census Tract 9801, Bexar County, Texas",5.667057,709,189,...,27,22,9.5,7.9,12898,1925865,0.000368,48029.0,89502,1544.0
361,48,TEXAS,TX,48029,Bexar,48029110100,"Census Tract 1101, Bexar County, Texas",1.364296,3102,365,...,272,130,11.3,5.0,38328,1925865,0.001611,48029.0,89502,1544.0
362,48,TEXAS,TX,48029,Bexar,48029110600,"Census Tract 1106, Bexar County, Texas",0.758136,5301,486,...,690,265,24.5,7.4,6776,1925865,0.002753,48029.0,89502,1544.0

In [ ]:
casesdf = pd.read_csv('COVID20201208_county', index_col=0)

In [ ]:
casesdf.head()

In [ ]:
# list of US zip codes with county and population, also includes county weights
countydf = pd.read_csv('uszips.csv')

In [ ]:
countydf

In [ ]:
countydf[countydf.county_name == 'Bexar']
# shows 70 zip codes for Bexar county

In [ ]:
countydf[countydf.county_name == 'Dallas']
# shows 117 rows for Dallas, other states have a Dallas county

In [ ]:
# filter for Dallas county TX only
countydf[(countydf.county_name == 'Dallas') & (countydf.state_id == 'TX')]

In [ ]:
# unpack county weights?
countydf.county_weights = countydf.county_weights.str.strip('{')
countydf.county_weights = countydf.county_weights.str.strip('}')
county_weightsdf = countydf.county_weights.str.split(',', expand=True)
county_weightsdf.columns = ['zip1', 'zip2', 'zip3', 'zip4', 'zip5', 'zip6']

tidy_df = pd.concat([countydf, county_weightsdf], axis=1).drop(columns='county_weights')
tidy_df

In [ ]:
tidy_df1 = tidy_df.zip1.str.split(':', expand=True)
tidy_df1.columns = ['zip_1', 'zip_1prcnt']

tidy_df1 = pd.concat([tidy_df, tidy_df1], axis=1).drop(columns='zip1')
tidy_df1

In [ ]:
tidy_df1.zip_1 = tidy_df1.zip_1.str.strip("'")

tidy_df2 = tidy_df1.zip2.str.split(':', expand=True)
tidy_df2.columns = ['zip_2', 'zip_2prcnt']

tidy_df2 = pd.concat([tidy_df1, tidy_df2], axis=1).drop(columns='zip2')
tidy_df2

In [ ]:
tidy_df2.zip_2 = tidy_df2.zip_2.str.strip("'")

tidy_df3 = tidy_df2.zip3.str.split(':', expand=True)
tidy_df3.columns = ['zip_3', 'zip_3prcnt']

tidy_df3 = pd.concat([tidy_df2, tidy_df3], axis=1).drop(columns='zip3')
tidy_df3

In [ ]:
tidy_df3.zip_3 = tidy_df3.zip_3.str.strip("'")

tidy_df4 = tidy_df3.zip4.str.split(':', expand=True)
tidy_df4.columns = ['zip_4', 'zip_4prcnt']

tidy_df4 = pd.concat([tidy_df3, tidy_df4], axis=1).drop(columns='zip4')
tidy_df4

In [ ]:
tidy_df4.to_csv('check_tidy.csv')

In [ ]:
all_dates = pd.read_csv('us-counties_COVID_all_dates.csv')

In [ ]:
all_dates.head()

In [ ]:
all_counties20201208 = all_dates[all_dates.date == '2020-12-08']

In [ ]:
all_counties20201208[all_counties20201208.county == 'Bexar']

In [ ]:
all_counties20201208.to_csv('COVID20201208_county')

In [ ]:
date1208 = pd.read_csv('COVID20201208_county', index_col = 0)

In [ ]:
date1208

In [ ]:
# merge zip to county for datae 12/8 ?? use inner join? will lose Puerto Rico I think
# need to isolate to Texas? other states have a Dallas county
zip_1208_county = pd.merge(countydf, date1208, left_on='county_name', right_on='county')

In [ ]:
zip_1208_county.shape

In [ ]:
zip_1208_county[zip_1208_county.county_name == 'Bexar']
# good, still have 70 zip codes for Bexar

In [ ]:
zip_1208_county[(zip_1208_county.county_name == 'Dallas') & (zip_1208_county.state_id == 'TX')]
# good, still have 70 zip codes for Bexar

In [ ]:
# test Dallas compile
dallasdf = acquire.compile_dallas_data()

In [ ]:
dallasdf.isna().sum()

In [ ]:
dallasdf.shape

In [ ]:
null_list = dallasdf[dallasdf.cases_per_100k.isna()].zip.tolist()

In [ ]:
# there are 62 zip codes in the Dallas SVI that are not showing in the list of cases
len(set(null_list))

In [ ]:
set(null_list)

In [ ]:
ddf = acquire.get_dallas_data()

In [ ]:
ddf.info()

In [ ]:
ddf

In [ ]:
dsvi = acquire.get_dallas_svi_data()

In [ ]:
dsvi.shape

In [ ]:
svi_zip = pd.merge(dsvi, mer, on='tract', how='left')

In [ ]:
svi_zip[svi_zip.zip.isna()]

In [ ]:
mer = acquire.get_HUD(dsvi)

In [ ]:
len(mer)

In [ ]:
mer.head()

In [ ]:
mer[mer.tract == 48113001701]

In [ ]:
mer[mer.tract == 48113020700]